# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `booleans` gem.
# Please instead update this file by running `bin/tapioca gem booleans`.


# source://booleans//lib/booleans/kernel_extension.rb#4
module Booleans; end

# Add the Boolean method to Kernel
#
# source://booleans//lib/booleans/kernel_extension.rb#6
module Booleans::KernelExtension
  # Convert a Ruby value to `true` or `false`
  # according to the truthiness of the value.
  #
  # Most Ruby objects get converted to `true` with the
  # exception of: `nil` and `false`.
  #
  # source://booleans//lib/booleans/kernel_extension.rb#15
  sig { params(val: T.anything).returns(T::Boolean) }
  def Boolean(val); end
end

module Kernel
  include ::Booleans::KernelExtension
end
