# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `shale-builder` gem.
# Please instead update this file by running `bin/tapioca gem shale-builder`.


# source://shale-builder//lib/shale/builder/version.rb#3
module Shale; end

# source://shale-builder//lib/shale/attribute.rb#7
class Shale::Attribute
  # Contains the documentation comment for the shale attribute
  # in a Ruby String.
  #
  # source://shale-builder//lib/shale/attribute.rb#24
  sig { returns(T.nilable(T::Array[::Symbol])) }
  def aliases; end

  # Contains the documentation comment for the shale attribute
  # in a Ruby String.
  #
  # source://shale-builder//lib/shale/attribute.rb#24
  def aliases=(_arg0); end

  # source://shale-builder//lib/shale/attribute.rb#27
  sig { returns(T::Array[::Symbol]) }
  def all_names; end

  # Returns `true` if the attribute is handled by a shale builder.
  #
  #
  # source://shale-builder//lib/shale/attribute.rb#45
  sig { returns(T::Boolean) }
  def builder?; end

  # Contains the documentation comment for the shale attribute
  # in a Ruby String.
  #
  # source://shale-builder//lib/shale/attribute.rb#19
  sig { returns(T.nilable(::String)) }
  def doc; end

  # Contains the documentation comment for the shale attribute
  # in a Ruby String.
  #
  # source://shale-builder//lib/shale/attribute.rb#19
  def doc=(_arg0); end

  # Returns `true` if the attribute is handled by a shale mapper.
  #
  #
  # source://shale-builder//lib/shale/attribute.rb#38
  sig { returns(T::Boolean) }
  def mapper?; end

  # source://shale-builder//lib/shale/attribute.rb#14
  sig { returns(T.untyped) }
  def return_type; end

  # source://shale-builder//lib/shale/attribute.rb#14
  def return_type=(_arg0); end

  # source://shale-builder//lib/shale/attribute.rb#11
  sig { returns(T.untyped) }
  def setter_type; end

  # source://shale-builder//lib/shale/attribute.rb#11
  def setter_type=(_arg0); end
end

# It's meant to be included in subclasses of `Shale::Mapper`
# to provide an easier way of building instances.
#
# Example:
#
#       require 'shale/builder'
#
#       class PaymentInstrument < Shale::Mapper
#         include Shale::Builder
#
#         attribute :number, Shale::Type::String
#         attribute :expiration_year, ::Shale::Type::Integer
#         attribute :expiration_month, ::Shale::Type::Integer
#       end
#
#       class Transaction < ::Shale::Mapper
#         include Shale::Builder
#
#         attribute :cvv_code, Shale::Type::String
#         attribute :payment_instrument, PaymentInstrument
#       end
#
#       transaction = Transaction.build do |t|
#           t.cvv_code = '123'
#           t.payment_instrument do |p|
#               p.number = '4242424242424242'
#               p.expiration_year = 2045
#               p.expiration_month = 12
#           end
#       end
#
#
# source://shale-builder//lib/shale/builder/version.rb#4
module Shale::Builder
  requires_ancestor { Object }

  mixes_in_class_methods ::Shale::Builder::ClassMethods

  # Returns an array of shale values
  # that have been assigned.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#211
  sig { returns(T::Array[::Shale::Builder::Value]) }
  def attribute_values; end

  # Attempts to set the given attributes and values
  # within this shale builder object and all of its sub-builders.
  # Attributes that aren't defined are ignored.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#223
  sig { params(context: T.untyped).void }
  def inject_context(**context); end

  class << self
    # Gets called after including this module in a module or class.
    #
    # source://shale-builder//lib/shale/builder.rb#57
    sig { params(mod: ::Module).void }
    def included(mod); end

    # Prepares the received module or class
    # for dynamic method definition.
    #
    # source://shale-builder//lib/shale/builder.rb#65
    sig { params(mod: ::Module).void }
    def prepare_mod(mod); end
  end
end

# Class methods provided by `Shale::Builder`
#
# @abstract Subclasses must implement the `abstract` methods below.
#
# source://shale-builder//lib/shale/builder.rb#73
module Shale::Builder::ClassMethods
  extend T::Generic

  abstract!

  has_attached_class!

  # Create an alias for the getter and setter of an attribute.
  #
  # source://shale-builder//lib/shale/builder.rb#153
  sig { params(new_name: ::Symbol, old_name: ::Symbol).void }
  def alias_attribute(new_name, old_name); end

  # source://shale-builder//lib/shale/builder.rb#106
  sig do
    params(
      name: T.any(::String, ::Symbol),
      shale_mapper: ::Class,
      collection: T::Boolean,
      default: T.nilable(::Proc),
      doc: T.nilable(::String),
      return_type: T.untyped,
      setter_type: T.untyped,
      kwargs: ::Object,
      block: T.nilable(T.proc.void)
    ).void
  end
  def attribute(name, shale_mapper, collection: T.unsafe(nil), default: T.unsafe(nil), doc: T.unsafe(nil), return_type: T.unsafe(nil), setter_type: T.unsafe(nil), **kwargs, &block); end

  # @abstract
  #
  # source://shale-builder//lib/shale/builder.rb#103
  sig { abstract.returns(T::Hash[::Symbol, ::Shale::Attribute]) }
  def attributes; end

  # @yield [body]
  #
  # source://shale-builder//lib/shale/builder.rb#92
  sig { params(_block: T.proc.params(arg0: T.attached_class).void).returns(T.attached_class) }
  def build(&_block); end

  # Returns a hash of shale attributes that are handled by a shale builder.
  # The result gets memoized.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#190
  sig { returns(T::Hash[::Symbol, ::Shale::Attribute]) }
  def builder_attributes; end

  # Returns a hash of shale attributes that are handled by a shale builder.
  # Always constructs a new hash.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#198
  sig { returns(T::Hash[::Symbol, ::Shale::Attribute]) }
  def builder_attributes!; end

  # Contains overridden getter methods for attributes
  # with complex types (so that they accept a block for building)
  #
  # source://shale-builder//lib/shale/builder.rb#89
  sig { returns(::Module) }
  def builder_methods_module; end

  # source://shale-builder//lib/shale/builder.rb#81
  sig { params(subclass: ::Class).void }
  def inherited(subclass); end

  # Returns a hash of shale attributes that are handled by a shale mapper.
  # The result gets memoized.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#172
  sig { returns(T::Hash[::Symbol, ::Shale::Attribute]) }
  def mapper_attributes; end

  # Returns a hash of shale attributes that are handled by a shale mapper.
  # Always constructs a new hash.
  #
  #
  # source://shale-builder//lib/shale/builder.rb#180
  sig { returns(T::Hash[::Symbol, ::Shale::Attribute]) }
  def mapper_attributes!; end

  # @abstract
  #
  # source://shale-builder//lib/shale/builder.rb#100
  sig { abstract.params(props: T.anything).returns(T.attached_class) }
  def new(**props); end
end

# source://shale-builder//lib/shale/builder.rb#50
Shale::Builder::S = Shale::Type

# source://shale-builder//lib/shale/builder/version.rb#5
Shale::Builder::VERSION = T.let(T.unsafe(nil), String)

# Represents a value of a particular shale attribute.
# Hold the value and a reference to the attribute definition.
#
# source://shale-builder//lib/shale/builder/value.rb#10
class Shale::Builder::Value
  # source://shale-builder//lib/shale/builder/value.rb#24
  sig { params(attribute: ::Shale::Attribute, value: T.untyped).void }
  def initialize(attribute, value); end

  # Shale attribute definition
  #
  #
  # source://shale-builder//lib/shale/builder/value.rb#16
  sig { returns(::Shale::Attribute) }
  def attribute; end

  # Value of the attribute.
  #
  #
  # source://shale-builder//lib/shale/builder/value.rb#21
  sig { returns(T.untyped) }
  def value; end
end
