# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-box` gem.
# Please instead update this file by running `bin/tapioca gem tty-box`.


# source://tty-box//lib/tty/box/border.rb#3
module TTY; end

# source://tty-box//lib/tty/box/border.rb#4
module TTY::Box
  private

  # Bottom border
  #
  # @api private
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#493
  def bottom_border(title, width, border, style); end

  # Bottom left corner
  #
  # @api private
  # @param border [Border]
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#455
  def bottom_left_corner(border); end

  # Bottom right corner
  #
  # @api private
  # @param border [Border]
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#469
  def bottom_right_corner(border); end

  # Bottom space taken by titles and corners
  #
  # @api private
  # @return [Integer]
  #
  # source://tty-box//lib/tty/box.rb#441
  def bottom_space_taken(title, border); end

  # Bottom titles size
  #
  # @api private
  # @return [Integer]
  #
  # source://tty-box//lib/tty/box.rb#481
  def bottom_titles_size(title); end

  # source://tty-box//lib/tty/box.rb#73
  def color(enabled: T.unsafe(nil)); end

  # Convert content array to string
  #
  # @api private
  # @param content [Array<String>]
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#275
  def content_to_str(content); end

  # The maximum content width for all the lines
  #
  # @api private
  # @param lines [Array<String>]
  # @return [Integer]
  #
  # source://tty-box//lib/tty/box.rb#307
  def content_width(lines); end

  # source://tty-box//lib/tty/box.rb#37
  def corner_bottom_left_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#25
  def corner_bottom_right_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#33
  def corner_top_left_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#29
  def corner_top_right_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#65
  def cross_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#69
  def cursor; end

  # source://tty-box//lib/tty/box.rb#49
  def divider_down_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#41
  def divider_left_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#53
  def divider_right_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#45
  def divider_up_char(border = T.unsafe(nil)); end

  # A frame for error type message
  #
  # @api public
  # @param message [String] the message to display
  #
  # source://tty-box//lib/tty/box.rb#152
  def error(message, **opts); end

  # Convert style keywords into styling
  #
  # @api private
  # @return [Array[Proc, Proc]]
  #
  # source://tty-box//lib/tty/box.rb#353
  def extract_style(style); end

  # Format content by wrapping, aligning and padding out
  #
  # @api private
  # @param lines [Array<String>] the lines to format
  # @param width [Integer] the maximum width
  # @param padding [Integer, Array<Integer>] the amount of padding
  # @param align [Symbol] the type of alignment
  # @param separator [String] the newline separator
  # @return [Array[String]]
  #
  # source://tty-box//lib/tty/box.rb#330
  def format(lines, width, padding, align, separator); end

  # Create a frame
  #
  # @api public
  # @param top [Integer] the offset from the terminal top
  # @param left [Integer] the offset from the terminal left
  # @param width [Integer] the width of the box
  # @param height [Integer] the height of the box
  # @param align [Symbol] the content alignment
  # @param padding [Integer, Array[Integer]] the padding around content
  # @param title [Hash] the title for top or bottom border
  # @param border [Hash, Symbol] the border type
  # @param style [Hash] the styling for the front and background
  #
  # source://tty-box//lib/tty/box.rb#191
  def frame(*content, top: T.unsafe(nil), left: T.unsafe(nil), width: T.unsafe(nil), height: T.unsafe(nil), align: T.unsafe(nil), padding: T.unsafe(nil), title: T.unsafe(nil), border: T.unsafe(nil), style: T.unsafe(nil), enable_color: T.unsafe(nil)); end

  # Infer box dimensions based on content lines and padding
  #
  # @api private
  # @param lines [Array[String]]
  # @param padding [Array[Integer]|Integer]
  # @return [Array[Integer]]
  #
  # source://tty-box//lib/tty/box.rb#292
  def infer_dimensions(lines, padding); end

  # A frame for info type message
  #
  # @api public
  # @param message [String] the message to display
  #
  # source://tty-box//lib/tty/box.rb#83
  def info(message, **opts); end

  # source://tty-box//lib/tty/box.rb#57
  def line_char(border = T.unsafe(nil)); end

  # source://tty-box//lib/tty/box.rb#61
  def pipe_char(border = T.unsafe(nil)); end

  # A frame for for success type message
  #
  # @api public
  # @param message [String] the message to display
  #
  # source://tty-box//lib/tty/box.rb#129
  def success(message, **opts); end

  # Top border
  #
  # @api private
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#417
  def top_border(title, width, border, style); end

  # Top left corner
  #
  # @api private
  # @param border [Border]
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#379
  def top_left_corner(border); end

  # Top right corner
  #
  # @api private
  # @param border [Border]
  # @return [String]
  #
  # source://tty-box//lib/tty/box.rb#393
  def top_right_corner(border); end

  # Top space taken by titles and corners
  #
  # @api private
  # @return [Integer]
  #
  # source://tty-box//lib/tty/box.rb#365
  def top_space_taken(title, border); end

  # Top titles size
  #
  # @api private
  # @return [Integer]
  #
  # source://tty-box//lib/tty/box.rb#405
  def top_titles_size(title); end

  # A frame for warning type message
  #
  # @api public
  # @param message [String] the message to display
  #
  # source://tty-box//lib/tty/box.rb#106
  def warn(message, **opts); end

  class << self
    # source://tty-box//lib/tty/box.rb#73
    def color(enabled: T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#37
    def corner_bottom_left_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#25
    def corner_bottom_right_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#33
    def corner_top_left_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#29
    def corner_top_right_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#65
    def cross_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#69
    def cursor; end

    # source://tty-box//lib/tty/box.rb#49
    def divider_down_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#41
    def divider_left_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#53
    def divider_right_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#45
    def divider_up_char(border = T.unsafe(nil)); end

    # A frame for error type message
    #
    # @api public
    # @param message [String] the message to display
    #
    # source://tty-box//lib/tty/box.rb#152
    def error(message, **opts); end

    # Create a frame
    #
    # @api public
    # @param top [Integer] the offset from the terminal top
    # @param left [Integer] the offset from the terminal left
    # @param width [Integer] the width of the box
    # @param height [Integer] the height of the box
    # @param align [Symbol] the content alignment
    # @param padding [Integer, Array[Integer]] the padding around content
    # @param title [Hash] the title for top or bottom border
    # @param border [Hash, Symbol] the border type
    # @param style [Hash] the styling for the front and background
    #
    # source://tty-box//lib/tty/box.rb#191
    def frame(*content, top: T.unsafe(nil), left: T.unsafe(nil), width: T.unsafe(nil), height: T.unsafe(nil), align: T.unsafe(nil), padding: T.unsafe(nil), title: T.unsafe(nil), border: T.unsafe(nil), style: T.unsafe(nil), enable_color: T.unsafe(nil)); end

    # A frame for info type message
    #
    # @api public
    # @param message [String] the message to display
    #
    # source://tty-box//lib/tty/box.rb#83
    def info(message, **opts); end

    # source://tty-box//lib/tty/box.rb#57
    def line_char(border = T.unsafe(nil)); end

    # source://tty-box//lib/tty/box.rb#61
    def pipe_char(border = T.unsafe(nil)); end

    # A frame for for success type message
    #
    # @api public
    # @param message [String] the message to display
    #
    # source://tty-box//lib/tty/box.rb#129
    def success(message, **opts); end

    # A frame for warning type message
    #
    # @api public
    # @param message [String] the message to display
    #
    # source://tty-box//lib/tty/box.rb#106
    def warn(message, **opts); end

    private

    # Bottom border
    #
    # @api private
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#493
    def bottom_border(title, width, border, style); end

    # Bottom left corner
    #
    # @api private
    # @param border [Border]
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#455
    def bottom_left_corner(border); end

    # Bottom right corner
    #
    # @api private
    # @param border [Border]
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#469
    def bottom_right_corner(border); end

    # Bottom space taken by titles and corners
    #
    # @api private
    # @return [Integer]
    #
    # source://tty-box//lib/tty/box.rb#441
    def bottom_space_taken(title, border); end

    # Bottom titles size
    #
    # @api private
    # @return [Integer]
    #
    # source://tty-box//lib/tty/box.rb#481
    def bottom_titles_size(title); end

    # Convert content array to string
    #
    # @api private
    # @param content [Array<String>]
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#275
    def content_to_str(content); end

    # The maximum content width for all the lines
    #
    # @api private
    # @param lines [Array<String>]
    # @return [Integer]
    #
    # source://tty-box//lib/tty/box.rb#307
    def content_width(lines); end

    # Convert style keywords into styling
    #
    # @api private
    # @return [Array[Proc, Proc]]
    #
    # source://tty-box//lib/tty/box.rb#353
    def extract_style(style); end

    # Format content by wrapping, aligning and padding out
    #
    # @api private
    # @param lines [Array<String>] the lines to format
    # @param width [Integer] the maximum width
    # @param padding [Integer, Array<Integer>] the amount of padding
    # @param align [Symbol] the type of alignment
    # @param separator [String] the newline separator
    # @return [Array[String]]
    #
    # source://tty-box//lib/tty/box.rb#330
    def format(lines, width, padding, align, separator); end

    # Infer box dimensions based on content lines and padding
    #
    # @api private
    # @param lines [Array[String]]
    # @param padding [Array[Integer]|Integer]
    # @return [Array[Integer]]
    #
    # source://tty-box//lib/tty/box.rb#292
    def infer_dimensions(lines, padding); end

    # Top border
    #
    # @api private
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#417
    def top_border(title, width, border, style); end

    # Top left corner
    #
    # @api private
    # @param border [Border]
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#379
    def top_left_corner(border); end

    # Top right corner
    #
    # @api private
    # @param border [Border]
    # @return [String]
    #
    # source://tty-box//lib/tty/box.rb#393
    def top_right_corner(border); end

    # Top space taken by titles and corners
    #
    # @api private
    # @return [Integer]
    #
    # source://tty-box//lib/tty/box.rb#365
    def top_space_taken(title, border); end

    # Top titles size
    #
    # @api private
    # @return [Integer]
    #
    # source://tty-box//lib/tty/box.rb#405
    def top_titles_size(title); end
  end
end

# source://tty-box//lib/tty/box.rb#19
TTY::Box::BOX_CHARS = T.let(T.unsafe(nil), Hash)

# A class reponsible for retrieving border options
#
# @api private
#
# source://tty-box//lib/tty/box/border.rb#8
class TTY::Box::Border
  # @api private
  # @return [Border] a new instance of Border
  #
  # source://tty-box//lib/tty/box/border.rb#47
  def initialize(type: T.unsafe(nil), top: T.unsafe(nil), top_left: T.unsafe(nil), top_right: T.unsafe(nil), left: T.unsafe(nil), right: T.unsafe(nil), bottom: T.unsafe(nil), bottom_left: T.unsafe(nil), bottom_right: T.unsafe(nil)); end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom_left; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom_left?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom_right; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def bottom_right?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def left; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def left?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def right; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def right?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top_left; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top_left?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top_right; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def top_right?; end

  # @api private
  #
  # source://tty-box//lib/tty/box/border.rb#35
  def type; end

  private

  # Check if border values name is allowed
  #
  # @api private
  # @raise [ArgumentError]
  #
  # source://tty-box//lib/tty/box/border.rb#75
  def check_name(key, value); end

  class << self
    # @api private
    #
    # source://tty-box//lib/tty/box/border.rb#23
    def parse(border); end
  end
end

# @api private
#
# source://tty-box//lib/tty/box/border.rb#9
TTY::Box::Border::BORDER_VALUES = T.let(T.unsafe(nil), Array)

# source://tty-box//lib/tty/box.rb#17
TTY::Box::LINE_BREAK = T.let(T.unsafe(nil), Regexp)

# source://tty-box//lib/tty/box.rb#14
TTY::Box::NEWLINE = T.let(T.unsafe(nil), String)

# source://tty-box//lib/tty/box.rb#15
TTY::Box::SPACE = T.let(T.unsafe(nil), String)

# source://tty-box//lib/tty/box/version.rb#5
TTY::Box::VERSION = T.let(T.unsafe(nil), String)
