gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - amazing_print
  - rbi
  - rspec
  - spoom
  - rubocop
  - yard
  - yard-sorbet
  - prism
  - rdoc
  - debug
  - tapioca
  - language_server-protocol
  - rubocop-ast
  - rubocop-sorbet
  - parser
  - regexp_parser
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
