# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Capistrano::DataPlaneApi::Type`.
# Please instead update this file by running `bin/tapioca dsl Capistrano::DataPlaneApi::Type`.


class Capistrano::DataPlaneApi::Type
  include ShaleAttributeMethods

  module ShaleAttributeMethods; end
end
